### ISSUE TITLE
Question: Is there any way to get the type of a function from index?

### ISSUE THREAD

**Issue by pushldr** [Qwokka/WAIL#6]
(Awesome tool first of all) I want to be able to edit/call a function without knowing originally what the target method looks like. Like the title says, is there a way I get the params/return type from a function index to help with this?
Something like?
```js
const funcIndex = wail.getFunctionIndex(0);
const functionParams = wail.getFunctionParams(funcIndex);
const functionReturnType = wail.getFunctionReturnType(funcIndex);
```
Not sure if I'm making a lot of sense

**Comment by Qwokka** [comment]
Hey @pushldr ,

Unfortunately WAIL is probably a bad solution for this. The reason is WAIL is intended to parse the whole binary in a single pass rather than disecting the binary, modifying it, and putting it back together. A library like `libwabt.js` might be a better fit.

If you'd rather still with WAIL though, this could probably be done with a couple changes:

* Add a global FUNCTION entry parser that runs each time a function is parsed (Similar to `addCodeElementParser()`)
* Parse the binary twice passes:
    * First pass grabs the type data of the function
    * Second pass modifies the entry

**Comment by pushldr** [comment]
Thanks for the answer, that's unfortunate but I'll look into your suggestions however. (Still a really neat library regardless)
